# Generated by Django 5.2.3 on 2025-06-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_question_link_question_constraints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='examples',
            field=models.JSONField(default=list),
        ),
    ]
